### ISSUE TITLE
Incorrect label on photos - case details page

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#863] opened 2018-03-07 15:28 UTC
When a photo displays on a 'case details page' there is a 'create' label that appears on the image. This should not appear.

Example:
https://311.digital-staging.boston.gov/reports/18-00013609

![screen shot 2018-03-07 at 9 58 56 am](https://user-images.githubusercontent.com/20731897/37099496-6ac96b7a-21ee-11e8-9da9-a78a5065d6db.png)

There should be no caption at the bottom of the photo.

**Comment by fionawhim** [comment] 2018-03-07 17:00
Duplicate of #829, which I realize never made it to the 311 project.

**Closed as completed by fionawhim** 2018-03-07 17:00 UTC
Labels: productionization
