### ISSUE TITLE
Testing UAT search indexer

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#932] opened 2018-11-06 16:47 UTC
Test out bringing cases into the search indexer on UAT

**Comment by reillyzlab** [comment] 2018-11-07 14:26
Dave reports that at current rate the original data transfer/index will take 4-5 days for the mobile apps.

**Comment by fionawhim** [comment] 2018-11-20 21:08
Dupe of CityOfBoston/311-indexer#78

**Closed as completed by fionawhim** 2018-11-20 21:08 UTC
